```{r echo=FALSE}
library(tidyverse)
library(fontawesome)

due <- gsheet::gsheet2tbl(settings$schedule_url) %>%
  mutate(
    assign_due = lead(date, 1) - 1,
    assign_due = format(assign_due, format = "%B %d")) %>% 
  filter(class_num == params$number) %>%
  pull(assign_due) %>% 
  paste0(" by 11:59pm")

url_template <- paste0(
  'https://p4a.seas.gwu.edu/2022-Spring/templates/hw',
  params$number, '.zip')
```

> **Due**: `r due`
>
> **Submit**: To submit this assignment, create a zip file of all the files in your R project folder for this assignment. Name the zip file `r paste0('"hw', params$number, '-netID.zip"')`, replacing "netID" with your netID (e.g., `r paste0('"hw', params$number, '-jph.zip"')`). Use [this link](`r params$submit`) to submit your file.
>
> **Weight**: This assignment is worth 5% of your final grade.
>
> **Purpose**: `r params$purpose`
>
> **Assessment**: Each question indicates the % of the assignment grade, summing to 100%. The credit for each question will be assigned as follows:
>
> - 0% for not attempting a response.
> - 50% for attempting the question but with _major_ errors.
> - 75% for attempting the question but with _minor_ errors.
> - 100% for correctly answering the question.
> 
> The reflection portion is always worth 10% and graded for completion.
>
> **Rules**:
>
> - Problems marked **SOLO** may not be worked on with other classmates, though you may consult instructors for help.
> - For problems marked **COLLABORATIVE**, you may work in groups of up to 3 students who are in this course this semester. You may not split up the work -- everyone must work on every problem. And you may not simply copy any code but rather truly work together and submit your own solutions.